<?php

define('PHPUnit_MAIN_METHOD', 'Plugins_Fusioninventory_Agent::main');
    
if (!defined('GLPI_ROOT')) {
   define('GLPI_ROOT', '../../../..');
   $_SESSION['glpi_use_mode'] = 2;
   require_once GLPI_ROOT."/inc/includes.php";

   ini_set('display_errors','On');
   error_reporting(E_ALL | E_STRICT);
   set_error_handler("userErrorHandler");

}

/**
 * Test class for MyFile.
 * Generated by PHPUnit on 2010-08-06 at 12:05:09.
 */
class Plugins_Fusioninventory_Agent extends PHPUnit_Framework_TestCase {

    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Plugins_Fusioninventory_Agent');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

   public function testAgentCreation() {
      require_once 'emulatoragent.php';

      $input_xml = '<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>agenttest-2010-03-09-09-41-28</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>NTMXKUBJ</TOKEN>
</REQUEST>';

      $emulatorAgent = new emulatorAgent;
      $emulatorAgent->server_urlpath = "/glpi078/plugins/fusioninventory/front/communication.php";
      $return_xml = $emulatorAgent->sendProlog($input_xml);
      print_r($return_xml);

      $PluginFusioninventoryAgent = new PluginFusioninventoryAgent;
      $a_agent = $PluginFusioninventoryAgent->find("`device_id`='agenttest-2010-03-09-09-41-28'
                                                      AND token='NTMXKUBJ'
                                                      AND name='agenttest-2010-03-09-09-41-28'
                                                      AND last_contact IS NOT NULL");
      $this->assertEquals(count($a_agent), 1 , 'Problem on creation agent (have '.count($a_agent).' times in DB), code is '.$code);

   }

   

   public function testAgentDelete() {
      $PluginFusioninventoryAgent = new PluginFusioninventoryAgent;
      $a_agent = $PluginFusioninventoryAgent->find("`device_id`='agenttest-2010-03-09-09-41-28'
                                                      AND token='NTMXKUBJ'
                                                      AND name='agenttest-2010-03-09-09-41-28'
                                                      AND last_contact IS NOT NULL");
      $this->assertEquals(count($a_agent), 1 , 'Problem find agent (have '.count($a_agent).' times in DB)');
      if (count($a_agent) == '1') {
         foreach ($a_agent as $id=>$data) {
            $PluginFusioninventoryAgent->delete($data);
         }
      }
      $a_agent = $PluginFusioninventoryAgent->find("`device_id`='agenttest-2010-03-09-09-41-28'
                                                      AND token='NTMXKUBJ'
                                                      AND name='agenttest-2010-03-09-09-41-28'
                                                      AND last_contact IS NOT NULL");
      $this->assertEquals(count($a_agent), 0 , 'Unable to delete agent');
   }
   
   
}

// Call Plugins_Fusioninventory_Discovery_Newdevices::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Plugins_Fusioninventory_Agent::main') {
    Plugins_Fusioninventory_Agent::main();
}
?>