<?php

define('PHPUnit_MAIN_METHOD', 'Plugins_Fusioninventory_InventoryLocal::main');
    
if (!defined('GLPI_ROOT')) {
   define('GLPI_ROOT', '../../../..');

   if (!isset($_SESSION['glpilanguage'])) {
      $_SESSION['glpilanguage'] = 'en_GB';
   }
   $_SESSION['glpi_use_mode'] = 2;
   require_once GLPI_ROOT."/inc/includes.php";

   ini_set('display_errors','On');
   error_reporting(E_ALL | E_STRICT);
   set_error_handler("userErrorHandler");

}

/**
 * Test class for MyFile.
 * Generated by PHPUnit on 2010-08-06 at 12:05:09.
 */
class Plugins_Fusioninventory_InventoryLocal extends PHPUnit_Framework_TestCase {

    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Plugins_Fusioninventory_InventoryLocal');
        $result = PHPUnit_TextUI_TestRunner::run($suite);

    }


    public function testSetModuleInventoryOff() {
       global $DB;
       
        // set in config module inventory = yes by default
        $query = "UPDATE `glpi_plugin_fusioninventory_agentmodules`
           SET `is_active`='0'
           WHERE `modulename`='INVENTORY' ";
        $result = $DB->query($query);
       
    }


    public function testSendinventoryOff() {
       $this->testSendinventory();
    }


   public function testMachinesCriteriasFoldersOff() {
      $exist = 0;
      if (file_exists(GLPI_ROOT."/files/_plugins/fusioninventory/machines")) {
         $exist = 1;
      }
      $this->assertEquals($exist, 0 , 'Problem on inventory, machines & criterias folder must not create because inventory not allowed on this agent');
   }



    public function testSetModuleInventoryOn() {
       global $DB;
       
        // set in config module inventory = yes by default
        $query = "UPDATE `glpi_plugin_fusioninventory_agentmodules`
           SET `is_active`='1'
           WHERE `modulename`='INVENTORY' ";
        $result = $DB->query($query);
       
    }


    public function testSendinventory() {
      require_once 'emulatoragent.php';

      
      $input_xml = '<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>agenttest-2010-03-09-09-41-28</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>NTMXKUBJ</TOKEN>
</REQUEST>';

      $emulatorAgent = new emulatorAgent;
      $emulatorAgent->server_urlpath = "/glpi0780/plugins/fusioninventory/front/communication.php";
      // PROLOG. What can I do?
      $return_xml = $emulatorAgent->sendProlog($input_xml);
      echo "========== Prolog ==========\n";
      print_r($return_xml);

      $input_xml = file_get_contents("xml/inventory_local/2.1.5/port003-2010-06-08-08-13-45.xml");
      $input_xml = str_replace("<DEVICEID></DEVICEID>", "<DEVICEID>agenttest-2010-03-09-09-41-28</DEVICEID>", $input_xml);
      // Return Inventory you want
      $return_xml = $emulatorAgent->sendProlog($input_xml);
      echo "========== Send local inventory ==========\n";
      print_r($return_xml);

   }

   

   public function testMachinesCriteriasFolders() {
      $exist = 0;
      if (file_exists(GLPI_ROOT."/files/_plugins/fusioninventory/machines")) {
         $exist = 1;
      }
      $this->assertEquals($exist, 1 , 'Problem on inventory, machines & criterias folder not create successfully!');
   }

//
//
//   public function testComputerCreation() {
//
//   }
//
//
//   public function testComputerVolumes() {
//
//   }


   public function testSendinventoryByWebservice() {


      system('php ../../../webservices/scripts/testxmlrpc.php --method=glpi.doLogin --login_name=glpi login_password=glpi',$data);


      $a_data = explode("\n", $output);
      foreach($a_data as $num=>$value) {
         if (strstr($value, "[session] => ")) {
            $session_num = str_replace("[session] => ", $value);
         }
      }

      system('php ../../../webservices/scripts/testxmlrpc.php method=fusioninventory.test --base64=plugins/fusioninventory/tools/phpunit/xml/inventory_local/2.1.6/port003-2010-06-08-08-13-45.xml --session='.$session_num, $data);
      print_r($data);
   }


}

// Call Plugins_Fusioninventory_Discovery_Newdevices::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Plugins_Fusioninventory_InventoryLocal::main') {
    Plugins_Fusioninventory_InventoryLocal::main();
}
?>