<?php

define('PHPUnit_MAIN_METHOD', 'Plugins_Fusioninventory_Discovery_Agent::main');
    
if (!defined('GLPI_ROOT')) {
   define('GLPI_ROOT', '../../../../..');
   $_SESSION['glpi_use_mode'] = 2;
   require_once GLPI_ROOT."/inc/includes.php";

   ini_set('display_errors','On');
   error_reporting(E_ALL | E_STRICT);
   set_error_handler("userErrorHandler");

}

/**
 * Test class for MyFile.
 * Generated by PHPUnit on 2010-08-06 at 12:05:09.
 */
class Plugins_Fusioninventory_Discovery_Agent extends PHPUnit_Framework_TestCase {

    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Plugins_Fusioninventory_Discovery_Agent');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

   public function testAgentCreation() {

      $input_xml = '<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>agenttest-2010-03-09-09-41-28</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>NTMXKUBJ</TOKEN>
</REQUEST>';
      
      $PluginFusionInventoryCommunication = new PluginFusionInventoryCommunication;
      $code = $PluginFusionInventoryCommunication->importToken($input_xml);
      //if (($state == '2') OR ($state == '1')) { // agent created (2) + agent also created (1)
      $PluginFusionInventoryAgents = new PluginFusionInventoryAgents;
      $a_agent = $PluginFusionInventoryAgents->find("`key`='agenttest-2010-03-09-09-41-28'
                                                      AND token='NTMXKUBJ'
                                                      AND name='agenttest-2010-03-09-09-41-28'
                                                      AND last_agent_update IS NOT NULL");
      $this->assertEquals(count($a_agent), 1 , 'Problem on creation agent (have '.count($a_agent).' times in DB), code is '.$code);

   }


   public function testAgentDelete() {
      $PluginFusionInventoryAgents = new PluginFusionInventoryAgents;
      $a_agent = $PluginFusionInventoryAgents->find("`key`='agenttest-2010-03-09-09-41-28'
                                                      AND token='NTMXKUBJ'
                                                      AND name='agenttest-2010-03-09-09-41-28'
                                                      AND last_agent_update IS NOT NULL");
      $this->assertEquals(count($a_agent), 1 , 'Problem find agent (have '.count($a_agent).' times in DB)');
      if (count($a_agent) == '1') {
         foreach ($a_agent as $id=>$data) {
            $PluginFusionInventoryAgents->deleteFromDB($id);
         }
      }
      $a_agent = $PluginFusionInventoryAgents->find("`key`='agenttest-2010-03-09-09-41-28'
                                                      AND token='NTMXKUBJ'
                                                      AND name='agenttest-2010-03-09-09-41-28'
                                                      AND last_agent_update IS NOT NULL");
      $this->assertEquals(count($a_agent), 0 , 'Unable to delete agent');
   }
   
   
}

// Call Plugins_Fusioninventory_Discovery_Newdevices::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Plugins_Fusioninventory_Discovery_Agent::main') {
    Plugins_Fusioninventory_Discovery_Agent::main();
}
?>