== Fusioninventory Plugin

image:https://travis-ci.org/fusioninventory/fusioninventory-for-glpi.svg?branch=master["Build Status", link="https://travis-ci.org/fusioninventory/fusioninventory-for-glpi"]
image:https://coveralls.io/repos/fusioninventory/fusioninventory-for-glpi/badge.svg["Coverage Status", link="https://coveralls.io/r/fusioninventory/fusioninventory-for-glpi"]
image:https://img.shields.io/github/downloads/fusioninventory/fusioninventory-for-glpi/total.svg["github downloads"]
image:https://img.shields.io/badge/downloads%20redmine-218k total-brightgreen.svg["Redmine downloads"]

This plugin makes GLPI to process various types of tasks for Fusioninventory agents:

* Computer inventory
* Network discovery
* Network (SNMP) inventory
* Software deployment
* VMWare ESX host remote inventory

For further information and documentation, please check http://www.fusioninventory.org .

If you want to report bugs or check for development status, you can check http://forge.fusioninventory.org .

== Third-party code

* PluginFusioninventoryFindFiles() is copyright http://rosettacode.org/wiki/Walk_a_directory/Recursively#PHP[rosettacode.org] and
 made available under GNU Free Documentation License.

== Third-party icons and images

Some icons used in the project comes from the following set of
graphics licensed:

* Dortmund is copyright by http://pc.de/icons/[PC.DE] and made available under a
 http://creativecommons.org/licenses/by/3.0/deed[Creative Commons Attribution 3.0 License].

* Fugue Icons is copyright by http://p.yusukekamiyamane.com/[Yusuke Kamiyamame] and made
 available under a http://creativecommons.org/licenses/by/3.0/deed[Creative Commons Attribution 3.0 License].
