<?php

define('PHPUnit_MAIN_METHOD', 'Plugins_Fusioninventory_Discovery_Criteria::main');

//if (!defined(GLPI_ROOT)) {
   define('GLPI_ROOT', '../../../../..');
   $_SESSION['glpi_use_mode'] = 2;
   $NEEDED_ITEMS=array("computer","device","printer","networking","peripheral","monitor","software","infocom",
      "phone","tracking","enterprise","reservation","setup","group","registry","rulesengine","ocsng","admininfo",
      "rule.ocs","rule.softwarecategories","rule.dictionnary.software","rule.dictionnary.dropdown","entity");
   require_once GLPI_ROOT."/inc/includes.php";

   ini_set('display_errors','On');
   error_reporting(E_ALL | E_STRICT);
   set_error_handler("userErrorHandler");

//}

/**
 * Test class for MyFile.
 * Generated by PHPUnit on 2010-08-06 at 12:05:09.
 */
class Plugins_Fusioninventory_Discovery_Criteria extends PHPUnit_Framework_TestCase {

    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Plugins_Fusioninventory_Discovery_Criteria');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    
    /*
     * Test on Discovery mode :
     *  * Critere 1 : serial
     *  * Critere 2 : mac
     *
     *  * Ajout ordinateur avec carte reseau (IP + mac)
     *
     *  * Test avec ip, mac, nom d'un type ordinateur
     */

   public function testCriteriaDiscoveryMacaddress() {

      $Computer = new Computer();
      $Netport = new Netport();
      $PluginFusionInventoryConfig = new PluginFusionInventoryConfig;

      $PluginFusionInventoryConfig->getFromDB("1");
      
      $PluginFusionInventoryConfig->fields['criteria1_ip'] = 0;
      $PluginFusionInventoryConfig->fields['criteria1_name'] = 0;
      $PluginFusionInventoryConfig->fields['criteria1_serial'] = 1;
      $PluginFusionInventoryConfig->fields['criteria1_macaddr'] = 0;

      $PluginFusionInventoryConfig->fields['criteria2_ip'] = 0;
      $PluginFusionInventoryConfig->fields['criteria2_name'] = 0;
      $PluginFusionInventoryConfig->fields['criteria2_serial'] = 0;
      $PluginFusionInventoryConfig->fields['criteria2_macaddr'] = 1;

      $PluginFusionInventoryConfig->update($PluginFusionInventoryConfig->fields);

      $input = array();
      $input['name'] = "phpTestunit";
      $input["serial"] = "FGTYU4589H";
      $computer_id = $Computer->add($input);
      $input = array();
      $input['ifmac'] = "00:11:25:07:c6:22";
      $input['ifaddr'] = "192.168.0.32";
      $input['device_type'] = COMPUTER_TYPE;
      $input['on_device'] = $computer_id;
      $Netport->add($input);

      $p_criteria = array();
      $p_criteria['ip'] = "192.168.5.8";
      $p_criteria['name'] = "FTYGUHJ";
      $p_criteria['macaddr'] = "00:11:25:07:c6:22";
      $p_criteria['serial'] = trim("");
      $discovery_criteria = plugin_fusioninventory_discovery_criteria($p_criteria);

      if (!$discovery_criteria) {
         $this->assertEquals(1, 0 , 'Computer not finded with mac criteria');
      } else {

         $this->assertEquals($discovery_criteria, $computer_id."||".COMPUTER_TYPE , 'Not right computer finded ('.$discovery_criteria.')');
      }
      $Computer->deleteFromDB($computer_id);

   }


   // Same with 2 mac on this computer
   public function testCriteriaDiscovery2Macaddress() {

      $Computer = new Computer();
      $Netport = new Netport();
      $PluginFusionInventoryConfig = new PluginFusionInventoryConfig;

      $PluginFusionInventoryConfig->getFromDB("1");

      $PluginFusionInventoryConfig->fields['criteria1_ip'] = 0;
      $PluginFusionInventoryConfig->fields['criteria1_name'] = 0;
      $PluginFusionInventoryConfig->fields['criteria1_serial'] = 1;
      $PluginFusionInventoryConfig->fields['criteria1_macaddr'] = 0;

      $PluginFusionInventoryConfig->fields['criteria2_ip'] = 0;
      $PluginFusionInventoryConfig->fields['criteria2_name'] = 0;
      $PluginFusionInventoryConfig->fields['criteria2_serial'] = 0;
      $PluginFusionInventoryConfig->fields['criteria2_macaddr'] = 1;

      $PluginFusionInventoryConfig->update($PluginFusionInventoryConfig->fields);

      $input = array();
      $input['name'] = "phpTestunit";
      $input["serial"] = "FGTYU4589H";
      $computer_id = $Computer->add($input);
      $input = array();
      $input['ifmac'] = "00:11:25:07:c6:22";
      $input['ifaddr'] = "192.168.0.32";
      $input['device_type'] = COMPUTER_TYPE;
      $input['on_device'] = $computer_id;
      $Netport->add($input);
      $input = array();
      $input['ifmac'] = "00:11:25:07:c6:22";
      $input['ifaddr'] = "192.168.0.45";
      $input['device_type'] = COMPUTER_TYPE;
      $input['on_device'] = $computer_id;
      $Netport->add($input);

      $p_criteria = array();
      $p_criteria['name'] = "FTYGUHJ";
      $p_criteria['macaddr'] = "00:11:25:07:c6:22";
      $discovery_criteria = plugin_fusioninventory_discovery_criteria($p_criteria);

      if (!$discovery_criteria) {
         $this->assertEquals(1, 0 , 'Computer not finded with mac criteria');
      } else {

         $this->assertEquals($discovery_criteria, $computer_id."||".COMPUTER_TYPE , 'Not right computer finded ('.$discovery_criteria.')');
      }
      $Computer->deleteFromDB($computer_id);
   }



    /*
     * Test on Query mode :
     *  * Critere 1 : IP
     *  * Critere 2 : mac
     *
     *  * Ajout switch avec (IP + mac)
     *
     *  * Test avec ip, mac, nom d'un type materiel reseau
     */

   public function testCriteriaQueryIPMacaddress() {

      $Netdevice = new Netdevice;
      $Netport = new Netport();
      $PluginFusionInventoryConfig = new PluginFusionInventoryConfig;

      $PluginFusionInventoryConfig->getFromDB(1);

      $PluginFusionInventoryConfig->fields['criteria1_ip'] = 0;
      $PluginFusionInventoryConfig->fields['criteria1_name'] = 0;
      $PluginFusionInventoryConfig->fields['criteria1_serial'] = 1;
      $PluginFusionInventoryConfig->fields['criteria1_macaddr'] = 0;

      $PluginFusionInventoryConfig->fields['criteria2_ip'] = 1;
      $PluginFusionInventoryConfig->fields['criteria2_name'] = 0;
      $PluginFusionInventoryConfig->fields['criteria2_serial'] = 0;
      $PluginFusionInventoryConfig->fields['criteria2_macaddr'] = 1;

      $PluginFusionInventoryConfig->update($PluginFusionInventoryConfig->fields);

      $input = array();
      $input['name'] = "phpTestunit";
      $input["serial"] = "FGTYU4589H";
      $input['ifmac'] = "00:11:25:07:c6:22";
      $input['ifaddr'] = "192.168.0.32";
      $netdevice_id = $Netdevice->add($input);
      $p_criteria = array();
      $p_criteria['macaddr'] = "00:11:25:07:c6:22";
      $criteria['serial']  = "";
      $criteria['name']    = "ferf";
      $discovery_criteria = plugin_fusioninventory_discovery_criteria($p_criteria, NETWORKING_TYPE);

      if (!$discovery_criteria) {
         $this->assertEquals(1, 0 , 'Switch not finded with mac criteria');
      } else {

         $this->assertEquals($discovery_criteria, $netdevice_id , 'Not right switch finded ('.$discovery_criteria.')');
      }
      $Netdevice->deleteFromDB($netdevice_id);
   }
}

// Call Plugins_Fusioninventory_Discovery_Newdevices::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Plugins_Fusioninventory_Discovery_Criteria::main') {
    Plugins_Fusioninventory_Discovery_Criteria::main();
}
?>