<?php

define('PHPUnit_MAIN_METHOD', 'Plugins_Fusioninventory_Discovery_Newdevices::main');
    
if (!defined('GLPI_ROOT')) {
   define('GLPI_ROOT', '../../../../..');
   $_SESSION['glpi_use_mode'] = 2;
   require_once GLPI_ROOT."/inc/includes.php";

   ini_set('display_errors','On');
   error_reporting(E_ALL | E_STRICT);
   set_error_handler("userErrorHandler");

}

/**
 * Test class for MyFile.
 * Generated by PHPUnit on 2010-08-06 at 12:05:09.
 */
class Plugins_Fusioninventory_Discovery_Newdevices extends PHPUnit_Framework_TestCase {

    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Plugins_Fusioninventory_Discovery_Newdevices');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

   public function testDiscoverySwitchCisco() {

      $input_xml = '<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHSNMP>2</AUTHSNMP>
      <DESCRIPTION>Cisco IOS Software, C2960 Software (C2960-LANBASEK9-M), Version 12.2(52)SE, RELEASE SOFTWARE (fc3)^M
Copyright (c) 1986-2009 by Cisco Systems, Inc.^M
Compiled Fri 25-Sep-09 08:49 by sasyamal</DESCRIPTION>
      <ENTITY>15</ENTITY>
      <IP>192.168.0.80</IP>
      <MAC>00:1a:6c:9a:fc:80</MAC>
      <MODELSNMP>Networking0088</MODELSNMP>
      <SERIAL>FOC1567KYBT</SERIAL>
      <SNMPHOSTNAME>switch2960-001</SNMPHOSTNAME>
      <TYPE>2</TYPE>
    </DEVICE>
    <MODULEVERSION>1.1</MODULEVERSION>
    <PROCESSNUMBER>1280906135/001</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>agenttest-2010-03-09-09-41-28</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
';
      $PluginFusionInventoryCommunication = new PluginFusionInventoryCommunication;
      $code = $PluginFusionInventoryCommunication->import($input_xml);
      $this->assertFalse(!$code);

   }

   /*

    <DEVICE>
      <AUTHSNMP>1</AUTHSNMP>
      <DESCRIPTION>Photosmart D7200 series</DESCRIPTION>
      <ENTITY>15</ENTITY>
      <IP>192.168.0.151</IP>
      <MAC>00:21:5A:0B:BB:C4</MAC>
      <MODELSNMP>Printer0093</MODELSNMP>
      <NETBIOSNAME>HP00215A0BBBC4</NETBIOSNAME>
      <SERIAL></SERIAL>
      <SNMPHOSTNAME>HP0BBBC4</SNMPHOSTNAME>
      <TYPE>3</TYPE>
    </DEVICE>

    */
   
}

// Call Plugins_Fusioninventory_Discovery_Newdevices::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Plugins_Fusioninventory_Discovery_Newdevices::main') {
    Plugins_Fusioninventory_Discovery_Newdevices::main();
}
?>