<?php

define('PHPUnit_MAIN_METHOD', 'Plugins_Fusioninventory_Discovery_SnmpInventory::main');
    
if (!defined('GLPI_ROOT')) {
   define('GLPI_ROOT', '../../../../..');
   $_SESSION['glpi_use_mode'] = 2;
   $NEEDED_ITEMS=array("computer","device","printer","networking","peripheral","monitor","software","infocom",
      "phone","tracking","enterprise","reservation","setup","group","registry","rulesengine","ocsng","admininfo",
      "rule.ocs","rule.softwarecategories","rule.dictionnary.software","rule.dictionnary.dropdown","entity");
   session_start();
   require_once GLPI_ROOT."/inc/includes.php";
   ini_set('display_errors','On');
   error_reporting(E_ALL | E_STRICT);
   set_error_handler("userErrorHandler");

}
if (!isset($_SESSION['glpilanguage'])) {
   $_SESSION['glpilanguage'] = 'en_GB';
}
require_once GLPI_ROOT."/plugins/fusioninventory/locales/".$_SESSION['glpilanguage'].".php";

/**
 * Test class for MyFile.
 * Generated by PHPUnit on 2010-08-06 at 12:05:09.
 */
class Plugins_Fusioninventory_Discovery_SnmpInventory extends PHPUnit_Framework_TestCase {

    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('Plugins_Fusioninventory_Discovery_SnmpInventory');
        $result = Plugins_Fusioninventory_Discovery_SnmpInventory::run($suite);
    }

   public function testQuerySwitchCisco() {

      $input_xml = $this->createAgent();
      $processnumber = $this->createProcess($input_xml);


      $PluginFusionInventoryCommunication = new PluginFusionInventoryCommunication;
      $PluginFusionInventoryAgentsProcesses = new PluginFusionInventoryAgentsProcesses;
      $PluginFusionInventoryUnknownDevice = new PluginFusionInventoryUnknownDevice;
      $PluginFusionInventoryHistoryConnections = new PluginFusionInventoryHistoryConnections;
      $Netdevice = new Netdevice;
      $Netport = new Netport;
      $Netwire = new Netwire;

      // ************************ Test 1 ************************ //

      $mac = '            <CONNECTION>
              <MAC>00:00:85:58:45:42</MAC>
            </CONNECTION>';
      $input_xml = $this->xmlfile($processnumber, $mac);
      
      $PluginFusionInventoryCommunication->import($input_xml);

      // Search in unknown devices the hub
      //
      // Test 1
      $a_switch = $Netdevice->find("`serial`='FOC1567KYBT'
                                    AND `name`='switch2960-001'
                                    AND `ram`='60'
                                    AND `ifmac`='00:1a:6c:9a:fc:80'
                                    AND `ifaddr`='192.168.0.80' ");
 
      $this->assertEquals(count($a_switch), 1 , 'Problem on update switch (have '.count($a_switch).' times in DB)');
      foreach ($a_switch as $id=>$data) {
         $a_ports = $Netport->find("`device_type`='".NETWORKING_TYPE."'
                         AND `on_device`='".$id."'
                         AND `name`='Fa0/1'
                         AND `ifmac`='00:24:51:2c:93:01'
                         AND `logical_number`='10001' ");
         $this->assertEquals(count($a_ports), 1 , 'Problem on create port (have '.count($a_ports).' times in DB)');
         foreach($a_ports as $port_id=>$port_data) {
            // Verification si le port sur lequel il est connecte est un port Link
            $port_link_hub = $Netwire->getOppositeContact($port_id);
            $port_link_hub_test1 = $port_link_hub;
            $Netport->getFromDB($port_link_hub);
            $this->assertEquals($Netport->fields['name'], 'Link' , 'Port of hub not a Link port');
            $Netport->getFromDB($port_link_hub);

            // Vérification de tous les ports du hub
            $a_port_hub = $Netport->find("`on_device`='".$Netport->fields['on_device']."'
                                          AND `device_type`='".$PluginFusionInventoryUnknownDevice->type."'
                                          AND (`name` != 'Link' OR `name` IS NULL)");
            $this->assertEquals(count($a_port_hub), 2 , 'Not have 2 ports on the hub (have '.count($a_port_hub).' in DB)');

            // Vérification que les ports créé sont connecte au matos avec les 2 mac
            $a_mac = array();
            $a_mac['00:00:85:58:45:42'] = 1;
            $a_mac['00:11:85:c7:40:94'] = 1;
            $count = 0;
            foreach ($a_port_hub as $a_port_hub_id=>$a_port_hub_data) {
               $portoposite = $Netwire->getOppositeContact($a_port_hub_id);
               $Netport->getFromDB($portoposite);
               if (isset($a_mac[$Netport->fields['ifmac']])) {
                  unset ($a_mac[$Netport->fields['ifmac']]);
                  $count++;
               }               
            }
            $this->assertEquals($count, 2 , 'Not have 2 right ports connected on the hub (have only '.$count.')');
            $this->assertEquals(count($a_mac), 0 , 'Have '.count($a_mac).' ports not connected on hub');

            // Verification que le port du switch Fa0/1 a bien eu un historique sur sa connexion
            $a_history = $PluginFusionInventoryHistoryConnections->find("`process_number`='".$processnumber."'
               AND (`FK_port_source`='".$port_id."' OR `FK_port_destination`='".$port_id."')");
            $this->assertEquals(count($a_history), 1 , 'Have '.count($a_history).' lines of history instead of 1');
         }
      }


      // ************************ Test 2 ************************ //
      $processnumber = $this->createProcess($input_xml);
      $mac = '            <CONNECTION>
              <MAC>00:00:85:58:45:41</MAC>
            </CONNECTION>';
      $input_xml = $this->xmlfile($processnumber, $mac);

      $PluginFusionInventoryCommunication->import($input_xml);

      // Search if have same hub and if 00:00:85:58:45:42 has been deleted and
      // 00:00:85:58:45:41 added
         $a_ports = $Netport->find("`device_type`='".NETWORKING_TYPE."'
                         AND `on_device`='".$id."'
                         AND `name`='Fa0/1'
                         AND `ifmac`='00:24:51:2c:93:01'
                         AND `logical_number`='10001' ");
         $this->assertEquals(count($a_ports), 1 , '[Test2] Problem on create port (have '.count($a_ports).' times in DB)');
         foreach($a_ports as $port_id=>$port_data) {
            // Verification si le port sur lequel il est connecte est un port Link
            $port_link_hub = $Netwire->getOppositeContact($port_id);
            $this->assertEquals($port_link_hub, $port_link_hub_test1 , '[Test2] Hub on same port of switch not the same and must don\'t re-create a hub');


            $Netport->getFromDB($port_link_hub);
            $this->assertEquals($Netport->fields['name'], 'Link' , 'Port of hub not a Link port');
            $Netport->getFromDB($port_link_hub);

            // Vérification de tous les ports du hub
            $a_port_hub = $Netport->find("`on_device`='".$Netport->fields['on_device']."'
                                          AND `device_type`='".$PluginFusionInventoryUnknownDevice->type."'
                                          AND (`name` != 'Link' OR `name` IS NULL)");
            $this->assertEquals(count($a_port_hub), 2 , '[Test2] Not have 2 ports on the hub (have '.count($a_port_hub).' in DB)');

            // Vérification que les ports créé sont connecte au matos avec les 2 mac
            $a_mac = array();
            $a_mac['00:00:85:58:45:41'] = 1;
            $a_mac['00:11:85:c7:40:94'] = 1;
            $count = 0;
            foreach ($a_port_hub as $a_port_hub_id=>$a_port_hub_data) {
               $portoposite = $Netwire->getOppositeContact($a_port_hub_id);
               $Netport->getFromDB($portoposite);
               if (isset($a_mac[$Netport->fields['ifmac']])) {
                  unset ($a_mac[$Netport->fields['ifmac']]);
                  $count++;
               }
            }
            $this->assertEquals($count, 2 , '[Test2] Not have 2 right ports connected on the hub (have only '.$count.')');
            $this->assertEquals(count($a_mac), 0 , '[Test2] Have '.count($a_mac).' ports not connected on hub');

            // Verification que le port du switch Fa0/1 n'a pas bouge
            $a_history = $PluginFusionInventoryHistoryConnections->find("`process_number`='".$processnumber."'
               AND (`FK_port_source`='".$port_id."' OR `FK_port_destination`='".$port_id."')");
            $this->assertEquals(count($a_history), 0 , 'Have '.count($a_history).' lines of history instead of 0 (Because hub don\'t move)');

         }

     // ************************ Test 3 (Remove a mac to have only one mac and must delete hub) ************************ //
      $processnumber = $this->createProcess($input_xml);
      $mac = '';
      $input_xml = $this->xmlfile($processnumber, $mac);

      $PluginFusionInventoryCommunication->import($input_xml);

      $a_ports = $Netport->find("`device_type`='".NETWORKING_TYPE."'
                         AND `on_device`='".$id."'
                         AND `name`='Fa0/1'
                         AND `ifmac`='00:24:51:2c:93:01'
                         AND `logical_number`='10001' ");
      foreach($a_ports as $port_id=>$port_data) {
            // Verification si le port sur lequel il est connecte est un port Link
            $port_link_hub = $Netwire->getOppositeContact($port_id);
            $Netport->getFromDB($port_link_hub);
            $this->assertNotEquals($Netport->fields['name'], 'Link' , 'Port device is hub link port');

            // Verification que le port du switch Fa0/1 a bien eu 2 historiques (une deconnexion hub et une connexion pc)
            $a_history = $PluginFusionInventoryHistoryConnections->find("`process_number`='".$processnumber."'
               AND (`FK_port_source`='".$port_id."' OR `FK_port_destination`='".$port_id."')");
            $this->assertEquals(count($a_history), 2 , 'Have '.count($a_history).' lines of history instead of 2');
      }

      // Delete agent
      $this->deleteAgent();

   }

   // *********************** FUNCTIONS used by test functions *********************** //

   function createAgent() {
      $input_xml = '<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>agenttest-2010-03-09-09-41-28</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>NTMXKUBJ</TOKEN>
</REQUEST>';

      $PluginFusionInventoryCommunication = new PluginFusionInventoryCommunication;
      $PluginFusionInventoryCommunication->importToken($input_xml);
      return $input_xml;
   }


   function createProcess($input_xml) {
      $PluginFusionInventoryAgentsProcesses = new PluginFusionInventoryAgentsProcesses;
      $a_input = array();
      $pxml = @simplexml_load_string($input_xml);
      $processnumber = $PluginFusionInventoryAgentsProcesses->addProcess($pxml);
      return $processnumber;
   }



   function deleteAgent() {
      
      $PluginFusionInventoryAgents = new PluginFusionInventoryAgents;
      $a_agent = $PluginFusionInventoryAgents->find("`key`='agenttest-2010-03-09-09-41-28'
                                                      AND token='NTMXKUBJ'
                                                      AND name='agenttest-2010-03-09-09-41-28'
                                                      AND last_agent_update IS NOT NULL");
      $this->assertEquals(count($a_agent), 1 , 'Problem find agent (have '.count($a_agent).' times in DB)');
      if (count($a_agent) == '1') {
         foreach ($a_agent as $id=>$data) {
            $PluginFusionInventoryAgents->deleteFromDB($id);
         }
      }
   }



   function xmlfile($processnumber,$mac) {
$input_xml = '<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <INFO>
        <COMMENTS>Cisco IOS Software, C2960 Software (C2960-LANBASEK9-M), Version 12.2(44)SE3, RELEASE SOFTWARE (fc2)
Copyright (c) 1986-2008 by Cisco Systems, Inc.
Compiled Mon 29-Sep-08 00:59 by nachen</COMMENTS>
        <FIRMWARE>12.2(44)SE3</FIRMWARE>
        <ID>82</ID>
        <IPS>
          <IP>192.168.0.80</IP>
        </IPS>
        <LOCATION>Baie_01</LOCATION>
        <MAC>00:1a:6c:9a:fc:80</MAC>
        <MEMORY>24</MEMORY>
        <MODEL>WS-C2960-24PC-L</MODEL>
        <NAME>switch2960-001</NAME>
        <RAM>60</RAM>
        <SERIAL>FOC1567KYBT</SERIAL>
        <TYPE>NETWORKING</TYPE>
        <UPTIME>86 days, 11:21:56.76</UPTIME>
      </INFO>
      <PORTS>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:00:85:58:43:95</MAC>
            </CONNECTION>
            <CONNECTION>
              <MAC>00:25:b3:0b:f3:f1</MAC>
            </CONNECTION>
            <CONNECTION>
              <MAC>00:0a:5e:01:b4:7c</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/7</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>564035286</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>1 minute, 02.32</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/7</IFNAME>
          <IFNUMBER>10007</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>1096652158</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:07</MAC>
          <TRUNK>1</TRUNK>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:11:85:c7:40:94</MAC>
            </CONNECTION>
';
 $input_xml .= $mac;
 $input_xml .= '          </CONNECTIONS>
          <IFDESCR>FastEthernet0/1</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>18847653</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>50 days, 16:41:29.21</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/1</IFNAME>
          <IFNUMBER>10001</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2026316806</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:01</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:12:79:47:6f:1d</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/23</IFDESCR>
          <IFINERRORS>1</IFINERRORS>
          <IFINOCTETS>1220040927</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>86 days, 09:51:40.20</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/23</IFNAME>
          <IFNUMBER>10023</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>4238895490</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:17</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <IFDESCR>FastEthernet0/17</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>167706777</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>62 days, 16:53:26.85</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/17</IFNAME>
          <IFNUMBER>10017</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2185937725</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:11</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <IFDESCR>Null0</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>0</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>0.00 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Nu0</IFNAME>
          <IFNUMBER>10501</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>0</IFOUTOCTETS>
          <IFSPEED>4294967295</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>1</IFTYPE>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:1d:92:01:6a:b8</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/24</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>1164918847</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>24 days, 06:34:16.11</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/24</IFNAME>
          <IFNUMBER>10024</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>1088130796</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:18</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:25:b3:19:b2:3d</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/18</IFDESCR>
          <IFINERRORS>2</IFINERRORS>
          <IFINOCTETS>798254928</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>86 days, 10:21:33.48</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/18</IFNAME>
          <IFNUMBER>10018</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>1838787744</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:12</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:08:02:89:20:b7</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/9</IFDESCR>
          <IFINERRORS>43</IFINERRORS>
          <IFINOCTETS>919612462</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>72 days, 15:46:33.72</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/9</IFNAME>
          <IFNUMBER>10009</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>3613324523</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:09</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>08:00:09:6d:80:63</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/12</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>69711243</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>21 days, 12:45:11.38</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/12</IFNAME>
          <IFNUMBER>10012</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>3027712425</IFOUTOCTETS>
          <IFSPEED>10000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:0c</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:01:e6:39:fe:e0</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/11</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>88444796</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>75 days, 18:09:49.40</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/11</IFNAME>
          <IFNUMBER>10011</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>3528686494</IFOUTOCTETS>
          <IFSPEED>10000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:0b</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CDP>1</CDP>
            <CONNECTION>
              <IFDESCR>GigabitEthernet0/2</IFDESCR>
              <IP>172.25.22.10</IP>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>GigabitEthernet0/2</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>1930736521</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>42.99 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Gi0/2</IFNAME>
          <IFNUMBER>10102</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>4078838314</IFOUTOCTETS>
          <IFSPEED>1000000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:1a</MAC>
          <TRUNK>1</TRUNK>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:08:02:89:5d:dd</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/13</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>1350771963</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>83 days, 09:25:48.89</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/13</IFNAME>
          <IFNUMBER>10013</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2388604276</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:0d</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:08:02:89:5d:0c</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/6</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>2210360519</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>86 days, 10:38:59.31</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/6</IFNAME>
          <IFNUMBER>10006</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2781810224</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:06</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CDP>1</CDP>
            <CONNECTION>
              <IFDESCR>GigabitEthernet0/5</IFDESCR>
              <IP>172.25.22.1</IP>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>GigabitEthernet0/1</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>3850731419</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>42.99 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Gi0/1</IFNAME>
          <IFNUMBER>10101</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>3325175546</IFOUTOCTETS>
          <IFSPEED>1000000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:19</MAC>
          <TRUNK>1</TRUNK>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:0b:cd:21:e4:d6</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/15</IFDESCR>
          <IFINERRORS>15</IFINERRORS>
          <IFINOCTETS>1980634466</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>85 days, 18:35:00.26</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/15</IFNAME>
          <IFNUMBER>10015</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>1863816820</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:0f</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:23:7d:46:5c:47</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/14</IFDESCR>
          <IFINERRORS>7600</IFINERRORS>
          <IFINOCTETS>514549217</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>86 days, 10:06:03.71</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/14</IFNAME>
          <IFNUMBER>10014</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>430046997</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:0e</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:00:85:38:01:5a</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/8</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>47621694</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>57 days, 12:44:01.21</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/8</IFNAME>
          <IFNUMBER>10008</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>3415743919</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:08</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:08:02:89:99:a5</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/10</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>1184657970</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>86 days, 10:16:57.75</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/10</IFNAME>
          <IFNUMBER>10010</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>1553302151</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:0a</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:08:02:41:08:78</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/3</IFDESCR>
          <IFINERRORS>2</IFINERRORS>
          <IFINOCTETS>1325359389</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>86 days, 10:31:45.72</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/3</IFNAME>
          <IFNUMBER>10003</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>3653482278</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:03</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:25:b3:0c:51:f9</MAC>
            </CONNECTION>
            <CONNECTION>
              <MAC>00:25:b3:0b:fd:7f</MAC>
            </CONNECTION>
            <CONNECTION>
              <MAC>00:1e:c1:42:f1:90</MAC>
            </CONNECTION>
            <CONNECTION>
              <MAC>00:1e:c1:42:f1:91</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/4</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>164197181</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>85 days, 16:54:35.68</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/4</IFNAME>
          <IFNUMBER>10004</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2595612941</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:04</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:25:b3:1a:60:ad</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/21</IFDESCR>
          <IFINERRORS>1</IFINERRORS>
          <IFINOCTETS>1299354213</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>86 days, 09:21:33.40</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/21</IFNAME>
          <IFNUMBER>10021</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>1631609182</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:15</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:25:b3:19:b2:3a</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/20</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>2746631902</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>85 days, 12:36:04.30</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/20</IFNAME>
          <IFNUMBER>10020</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2168364662</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:14</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:1d:92:ae:dd:7f</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/2</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>792929140</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>49.48 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/2</IFNAME>
          <IFNUMBER>10002</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>3036446489</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:02</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:17:08:2a:8e:89</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/16</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>2062522031</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>86 days, 10:07:23.82</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/16</IFNAME>
          <IFNUMBER>10016</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2645666909</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:10</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <IFDESCR>Vlan2</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>692247217</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>43.08 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Vl2</IFNAME>
          <IFNUMBER>2</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>187070405</IFOUTOCTETS>
          <IFSPEED>1000000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>53</IFTYPE>
          <MAC>00:24:51:2c:93:41</MAC>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:10:83:95:02:5a</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/19</IFDESCR>
          <IFINERRORS>31</IFINERRORS>
          <IFINOCTETS>94472908</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>14 days, 09:09:51.24</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/19</IFNAME>
          <IFNUMBER>10019</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>3914810553</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:13</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:00:85:74:61:c2</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/5</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>126002091</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>63 days, 16:17:20.45</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/5</IFNAME>
          <IFNUMBER>10005</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2025383390</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:05</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:00:85:74:5c:4a</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFDESCR>FastEthernet0/22</IFDESCR>
          <IFINERRORS>1462</IFINERRORS>
          <IFINOCTETS>553615774</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>42 days, 07:01:18.23</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Fa0/22</IFNAME>
          <IFNUMBER>10022</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>2063888898</IFOUTOCTETS>
          <IFSPEED>100000000</IFSPEED>
          <IFSTATUS>1</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:24:51:2c:93:16</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>computers</NAME>
              <NUMBER>104</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
        <PORT>
          <IFDESCR>Vlan1</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>0</IFINOCTETS>
          <IFINTERNALSTATUS>2</IFINTERNALSTATUS>
          <IFLASTCHANGE>39.30 seconds</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Vl1</IFNAME>
          <IFNUMBER>1</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>0</IFOUTOCTETS>
          <IFSPEED>1000000000</IFSPEED>
          <IFSTATUS>2</IFSTATUS>
          <IFTYPE>53</IFTYPE>
          <MAC>00:24:51:2c:93:40</MAC>
        </PORT>
      </PORTS>
    </DEVICE>
    <PROCESSNUMBER>'.$processnumber.'</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>agenttest-2010-03-09-09-41-28</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
';
      return $input_xml;
      
   }
}

// Call Plugins_Fusioninventory_Discovery_Newdevices::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'Plugins_Fusioninventory_Discovery_SnmpInventory::main') {
    Plugins_Fusioninventory_Discovery_SnmpInventory::main();
}
?>